# General settings
experiment_name: "ARNIQA_Experiment"
device: 0
seed: 27

#data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KADID10K"
#unseen_distortion_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KADID10K"

#data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/TID2013"
#unseen_distortion_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/TID2013"

data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/SPAQ"
unseen_distortipath: "E:/ARNIQA - SE - mix/ARNIQA/dataset/SPAQ"


#data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CSIQ"
#unseen_distortipath: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CSIQ"

#data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/LIVE"
#unseen_distortion_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/LIVE"

data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CLIVE"
unseen_distortion_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CLIVE"


data_base_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KONIQ10K"
unseen_distortion_path: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KONIQ10K"

data_base_path_kadid: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KADID10K"
data_base_path_tid: "E:/ARNIQA - SE - mix/ARNIQA/dataset/TID2013"
data_base_path_spaq: "E:/ARNIQA - SE - mix/ARNIQA/dataset/SPAQ"
data_base_path_csiq: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CSIQ"
data_base_path_clive: "E:/ARNIQA - SE - mix/ARNIQA/dataset/CLIVE"
data_base_path_koniq: "E:/ARNIQA - SE - mix/ARNIQA/dataset/KONIQ10K"
data_base_path_live: "E:/ARNIQA - SE - mix/ARNIQA/dataset/LIVE"

checkpoint_base_path: "E:/ARNIQA - SE - mix/ARNIQA/experiments/my_experiment/regressors"
checkpoint_frequency: 1

# Training settings
training:
  epochs: 30
  learning_rate: !!float 1e-3
  batch_size: 16
  num_workers: 20
  log_images_frequency: 1000
  resume_training: false
  #step_size: 5
  #gamma: 0.1
  dropout_rate: 0.1

  data:
    patch_size: 224   # patch size for training
    max_distortions: 4  # maximum number of distortions to apply. Must be in the range [0, 7]
    num_levels: 5   # number of distortion levels to consider. Must be in the range [1, 5]
    pristine_prob: 0.05   # probability of not distorting images during training


  optimizer:
    name: SGD
    momentum: 0.9
    weight_decay: !!float 1e-4

    #lr_scheduler_type: cosine

  lr_scheduler:
    name: CosineAnnealingWarmRestarts
    T_0: 1
    T_mult: 2
    eta_min: !!float 1e-6

# Validation
validation:
  frequency: 1
  num_splits: 10
  alpha: 0.1
  visualize: true
  #early_stopping:
  #  patience: 5
  #  min_delta: 0.001
  datasets:
    - kadid10k
    - tid2013
    - spaq
    - CSIQ

# Test
test:
  batch_size: 16
  num_workers: 20
  num_splits: 10
  grid_search: true
  alpha: 0.1
  crop_size: 224  # crop size for inference
  datasets:  # datasets to use for test
    - live
    - csiq
    - tid2013
    - kadid10k
    - flive
    - spaq

# Model
model:
  temperature: 0.1
  encoder:
    embedding_dim: 128
    pretrained: true
    use_norm: true
  se_block:
    use_se: true
    reduction: 16
    activation: relu

# Logging
logging:
  use_wandb: false